name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: qoxowkd0716
          WAKATIME_API_KEY: ${{ waka_337cf78d-dec9-4d45-b26f-d452ec031463 }}
